//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `SITM.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SITM;

/** @hidden */
public class _ClientCallbackPrxI extends com.zeroc.Ice._ObjectPrxI implements ClientCallbackPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
